Lesson 4
mrDonald009/Geekshop pull request #4
Opened 2021-03-04 11:25 UTC by mrDonald009

Валерий здравствуйте, к сожалению не хватило времени разобраться с последним заданием.
А так же заметил какую то ошибку с logout, так как после входа в аккаунт нет возможности выйти, посмотрите пожалуйста в чем я допустил ошибку..

2021-03-04 16:36 UTC, Vokler requested changes

2021-03-04 16:36 UTC, Vokler commented on authapp/views.py
> +    return HttpResponseRedirect(reverse('mainapp:index'))
Logout работает, все успешно.
Единственное здесь нужно изменить на `reverse('index')`

2021-03-05 07:57 UTC, mrDonald009 commented on authapp/views.py
> +    return HttpResponseRedirect(reverse('mainapp:index'))
Готово!

2021-03-05 21:11 UTC, Vokler approved these changes

2021-03-05 21:11 UTC, merged